---
title: "行政院環保署空氣品質監測分析"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library Import

```{r library, warning=FALSE, message=FALSE}
library(xml2)
library(dplyr)
library(plotly)
library(ggplot2)
```

## Data Import
```{r data_import}
pm2 <- read.csv("https://raw.githubusercontent.com/jason19970210/Test/master/PM25/pm25.csv",stringsAsFactors = F)
head(pm2)
```

## Data Processing

```{r data_processing,warning=FALSE,message=FALSE}
pm2$CO <- as.numeric(pm2$CO)
pm2$CO_8 <- as.numeric(pm2$CO_8)
pm2$O3 <- as.numeric(pm2$O3)
pm2$O3_8 <- as.numeric(pm2$O3_8)
pm2$PM25 <- as.numeric(pm2$PM25)
pm2[is.na(pm2)] <- 0
pm2['nag_lat'] <- -pm2['lat']
```

## Data Correlation Coefficient

#### Results
- 高度正相關：CO, NO2
- 不相關：O3,PM25 / O3_8,PM25 / O3_8,PM25_AVG / PM10,THC / PM10_AVG,THC
- 與THC(總碳氫化物)中度相關：CO, NO2

```{r cor, results='hide'}
cor(pm2$CO, pm2$CO_8)           # output = 0.856 高度正相關
cor(pm2$CO, pm2$NO2)            # output = 0.827 高度正相關
cor(pm2$CO, pm2$O3)             # output = -0.387 低度負相關
cor(pm2$CO, pm2$O3_8)           # output = -0.441 中度負相關
cor(pm2$CO, pm2$PM10)           # output = 0.388 低度正相關
cor(pm2$CO, pm2$PM10_AVG)       # output = 0.179 低度正相關
cor(pm2$CO, pm2$PM25)           # output = 0.241 低度正相關
cor(pm2$CO, pm2$PM25_AVG)       # output = 0.205 低度正相關
cor(pm2$CO, pm2$SO2)            # output = 0.595 中度正相關
cor(pm2$CO, pm2$THC)            # output = 0.411 中度正相關

cor(pm2$CO_8, pm2$NO2)          # output = 0.672 中度正相關
cor(pm2$CO_8, pm2$O3)           # output = -0.414 中度負相關
cor(pm2$CO_8, pm2$O3_8)         # output = -0.483 中度負相關
cor(pm2$CO_8, pm2$PM10)         # output = 0.264 低度正相關
cor(pm2$CO_8, pm2$PM10_AVG)     # output = 0.306 低度正相關
cor(pm2$CO_8, pm2$PM25)         # output = 0.265 低度正相關
cor(pm2$CO_8, pm2$PM25_AVG)     # output = 0.263 低度正相關
cor(pm2$CO_8, pm2$SO2)          # output = 0.410 中度正相關
cor(pm2$CO_8, pm2$THC)          # output = 0.325 低度正相關

cor(pm2$NO2, pm2$O3)            # output = -0.426 中度負相關
cor(pm2$NO2, pm2$O3_8)          # output = -0.527 中度負相關
cor(pm2$NO2, pm2$PM10)          # output = 0.366 低度正相關
cor(pm2$NO2, pm2$PM10_AVG)      # output = 0.114 低度正相關
cor(pm2$NO2, pm2$PM25)          # output = 0.321 低度正相關
cor(pm2$NO2, pm2$PM25_AVG)      # output = 0.198 低度正相關
cor(pm2$NO2, pm2$SO2)           # output = 0.654 中度正相關
cor(pm2$NO2, pm2$THC)           # output = 0.448 中度正相關

cor(pm2$O3, pm2$O3_8)           # output = 0.777 高度正相關
cor(pm2$O3, pm2$PM10)           # output = -0.109 低度負相關
cor(pm2$O3, pm2$PM10_AVG)       # output = -0.180 低度負相關
cor(pm2$O3, pm2$PM25)           # output = -0.008 不相關
cor(pm2$O3, pm2$PM25_AVG)       # output = 0.101 低度正相關
cor(pm2$O3, pm2$SO2)            # output = -0.125 低度負相關
cor(pm2$O3, pm2$THC)            # output = -0.232 低度負相關

cor(pm2$O3_8, pm2$PM10)         # output = -0.132 低度負相關
cor(pm2$O3_8, pm2$PM10_AVG)     # output = -0.255 低度負相關
cor(pm2$O3_8, pm2$PM25)         # output = -0.048 不相關
cor(pm2$O3_8, pm2$PM25_AVG)     # output = 0.031 不相關
cor(pm2$O3_8, pm2$SO2)          # output = -0.242 低度負相關
cor(pm2$O3_8, pm2$THC)          # output = -0.110 低度負相關

cor(pm2$PM10, pm2$PM10_AVG)     # output = 0.579 中度正相關
cor(pm2$PM10, pm2$PM25)         # output = 0.266 低度正相關
cor(pm2$PM10, pm2$PM25_AVG)     # output = 0.145 低度正相關
cor(pm2$PM10, pm2$SO2)          # output = 0.401 中度正相關
cor(pm2$PM10, pm2$THC)          # output = 0.150 低度正相關

cor(pm2$PM10_AVG, pm2$PM25)     # output = 0.265 低度正相關
cor(pm2$PM10_AVG, pm2$PM25_AVG) # output = 0.345 低度正相關
cor(pm2$PM10_AVG, pm2$SO2)      # output = 0.105 低度正相關
cor(pm2$PM10_AVG, pm2$THC)      # output = -0.038 不相關

cor(pm2$PM25, pm2$PM25_AVG)     # output = 0.777 高度正相關
cor(pm2$PM25, pm2$SO2)          # output = 0.293 低度正相關
cor(pm2$PM25, pm2$THC)          # output = 0.146 低度正相關

cor(pm2$PM25_AVG, pm2$SO2)      # output = 0.228 低度正相關
cor(pm2$PM25_AVG, pm2$THC)      # output = 0.057 不相關

cor(pm2$SO2, pm2$THC)           # output = 0.293 低度正相關
```


## Plots
```{r plots,warning=FALSE,message=FALSE}
pm2 %>% plot_ly(y = ~.$lat, x = ~.$lng, type = 'scatter', mode = 'markers', color = .$MainPollutant)
pm2 %>% plot_ly(x = ~.$nag_lat, y = ~.$lng, z = ~.$THC, type = 'scatter3d', mode = 'markers', color = .$CO)
pm2 %>% filter(.$THC > 0) %>% plot_ly(x = ~.$nag_lat, y = ~.$lng, z = ~.$THC, type = 'scatter3d', mode = 'markers', color = .$CO)
pm2 %>% plot_ly(x = ~.$nag_lat, y = ~.$lng, z = ~.$THC, type = 'scatter3d', mode = 'markers', color = .$NO2)
pm2 %>% filter(.$THC > 0) %>% plot_ly(x = ~.$nag_lat, y = ~.$lng, z = ~.$THC, type = 'scatter3d', mode = 'markers', color = .$NO2)
pm2 %>% plot_ly(x = ~.$lng, y = ~.$lat, type = 'scatter', mode = 'markers', color = .$THC)

qplot(NO2, CO, data = pm2,geom = c("point","smooth"))
qplot(log(NO2), log(CO), data = pm2,geom = c("point","smooth"))
```
